import Head from 'next/head';
import Image from 'next/image';
import Aboutpage from '../components/Aboutpage';
import Homepage from '../components/Homepage';
import Info from '../components/Info';
import Landing from '../components/Landing';
import Menupage from '../components/Menupage';
import Navbar from '../components/Navbar';
import Testimonialpage from '../components/Testimonialpage';

export default function Home() {
  return (
    <div className="   bg-[url(/images/background.jpg)] ">
      <Head>
        <title>buger-site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Homepage />
      <Info />
      <Menupage />
      <Aboutpage />
      <Testimonialpage />
    </div>
  );
}
